spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/shopsphere_product
    username: shopsphere
    password: shopsphere

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082
